"""added driver table

Revision ID: 709cde01aafc
Revises: bec102b4c699
Create Date: 2024-07-03 02:49:09.983219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709cde01aafc'
down_revision = 'bec102b4c699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    # ### end Alembic commands ###
